### ISSUE TITLE
High CPU Usage on Debian 8 Jessie

### ISSUE THREAD

**Issue by cares** [jajuk-team/jajuk#1985]
Hi Guys,

great work you have done with that player :) and i love it +100

and i blogged about it as beeing cool  http://dwaves.de/index.php/2015/03/19/cool-software-for-linux-jajuk-media-player-and-organizer/

problem: on my quadcore i5 (!) system (debian 8 jessie) jajuk is causing 75% cpu usage…
which might be in the straight after adding a lot of music… and might continue for several days? until jajuk completely indexed it’s database?

but 75% is a lot.

i wonder what to do.

http://dwaves.de/wp-content/uploads/2015/03/jajuk-75-percent-cpu-usage.png

best regards :) you can fix that :)

system is Linux DebianGiada 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt7-1 (2015-03-01) x86_64 GNU/Linux

**Comment by bflorat** [comment]
Thanks for the feedback. Apart from indexing and thumbnails creation, Jajuk cpu usage should be near 0% on modern hardware and your collection is not huge. 

Maybe your thumbnails are still building ? we you go to "Catalog view", do you have messages like 'building thumb for album XXX" ?

Please also send me privately your ~/.jajuk/jajuk.log file at http://florat.net/contact

**Comment by centic9** [comment]
No update on this one for a long time, please report some more details if this is still a problem, e.g. some Java CPU profiling using VisualVM or Java FlightRecorder. 

If you don't have that, then at least the Stracktrace of all threads of the Jajuk-process via "jstack <pid>" could give some hint. Also newer versions may have fixed this as well.
