### ISSUE TITLE
ghost in the machine

### ISSUE THREAD

**Issue by jajukandy** [jajuk-team/jajuk#1998]
after running jajuk for a few weeks (ubuntu14.04) every time i try starting the program i get told already running. Music plays, mplayer starts but no display. No process running (other than mplayer and java). I have done a purge of all files and re-installed and still have the same album playing in background and no display. Is there a file somewhere which purge misses that i need to manually delete? Had  to download banshee to play music but seems power hungry on my laptop (volume on 11 to drown out the fan!) any ideas?

**Comment by bflorat** [comment]
Jajuk is the java process itself. Try to kill it or close you session, then edit your <home>/.jajuk/conf.properties. What' the value of the jajuk.startup_display_mode property ? 
Try to set it to '0' and restart jajuk.

**Comment by jajukandy** [comment]
thanks for the reply. I thought there must be a corrupted configuration file. I cannot find this file anywhere - not in home, I can only see changelog, copyright and news
--------------------------------------------
On Thu, 17/12/15, Bertrand Florat <notifications@github.com> wrote:

 Subject: Re: [jajuk] ghost in the machine (#1998)
 To: "jajuk-team/jajuk" <jajuk@noreply.github.com>
 Cc: "jajukandy" <ja_whitby@yahoo.co.uk>
 Date: Thursday, 17 December, 2015, 20:15
 
 Jajuk is the java process itself.
 Try to kill it or close you session, then edit your
 /.jajuk/conf.properties. What' the value of the
 jajuk.startup_display_mode property ? 
 
 Try to set it to '0' and restart jajuk.
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by bflorat** [comment]
This file should be in ~/.jajuk directory .It is created automaticaly by Jajuk. I think you looked in the binary distribution instead. Can you please check again ?

**Comment by jajukandy** [comment]
up and running again thanks, I found and edited the file using file gui with ctrl H and edited with gedit. I spent a lot of time trying to find the file with terminal and edit withnano (sorry sticky keyboard) but could not find even with ls -al from home directory - I need more practice with unix! thanks again
--------------------------------------------
On Sat, 19/12/15, Bertrand Florat <notifications@github.com> wrote:

 Subject: Re: [jajuk] ghost in the machine (#1998)
 To: "jajuk-team/jajuk" <jajuk@noreply.github.com>
 Cc: "jajukandy" <ja_whitby@yahoo.co.uk>
 Date: Saturday, 19 December, 2015, 15:07
 
 This file should be in ~/.jajuk
 directory .It is created automaticaly by Jajuk. I think you
 looked in the binary distribution instead. Can you please
 check again ?
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by bflorat** [comment]
You need to use the ls -a (all) option to see hidden directories/files. Free tip : create an alias like this in you .bashrc   
alias l="ls -altr'
and use 'l' instead of 'ls'

BTW, did you note the previous value of the startup_display_mode property ?

**Comment by jajukandy** [comment]
display mode was 1. I have noticed some players dont exit when window is closed, not sure if ALT F4 closes program or just the window. I did use ls -a but from /home not /home/andy . Places (top left) Home Folder shows path as Home but displays /home/andy/ which confused me. I am trying to get the hang of the bash find command but it returns a lot of results, and doesnt search all subdirectories or hidden files. Thanks for the tip on alias - once I work out correct search format  I'll set up an alias.
--------------------------------------------
On Sat, 19/12/15, Bertrand Florat <notifications@github.com> wrote:

 Subject: Re: [jajuk] ghost in the machine (#1998)
 To: "jajuk-team/jajuk" <jajuk@noreply.github.com>
 Cc: "jajukandy" <ja_whitby@yahoo.co.uk>
 Date: Saturday, 19 December, 2015, 22:10
 
 You need to use the ls -a (all)
 option to see hidden directories/files. Free tip : create an
 alias like this in you .bashrc
 
 
 alias l="ls -altr'
 
 and use 'l' instead of 'ls'
 
 BTW, did you note the previous value of the
 startup_display_mode property ?
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by bflorat** [comment]
You were in systray-only mode (did you see the systray icon )? clicking on it should open the main window)

**Comment by jajukandy** [comment]
I'm pretty sure the icon did not appear
--------------------------------------------
On Mon, 21/12/15, Bertrand Florat <notifications@github.com> wrote:

 Subject: Re: [jajuk] ghost in the machine (#1998)
 To: "jajuk-team/jajuk" <jajuk@noreply.github.com>
 Cc: "jajukandy" <ja_whitby@yahoo.co.uk>
 Date: Monday, 21 December, 2015, 8:15
 
 You were in systray-only mode
 (did you see the systray icon )? clicking on it should open
 the main window)
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by bflorat** [comment]
OK . I already experienced that under Linux. Anyway, we'll drop the systray support in next release.
