### ISSUE TITLE
Warnings with debian custom package

### ISSUE THREAD

**Issue by bflorat** [jajuk-team/jajuk#2000]
From Gwen :
I try the update by download the .deb file, in Ubuntu 15.10 there's a warning message :
Lintian check results for /home/gwen/Téléchargements/jajuk_1.10.8-3_all.deb:
E: jajuk: arch-independent-package-contains-binary-or-object usr/share/jajuk/lib/libunix-java.so
E: jajuk: arch-independent-package-contains-binary-or-object usr/share/jajuk/lib64/libunix-java.so
E: jajuk: maintainer-address-malformed root root@helicon 

Note that the dep package is built from RPM using "alien" command.

Evaluation : maybe should we move .so files and check if we can override the email address.

**Comment by gkerdal** [comment]
Hi,

1) maintainer-address-malformed, what would you suggest : build a deb file without alien command or modify the existing one by extracting and modify the content ?

2) libunix-java.so : is this library steel required ? I removed it from my machine and I didntt notice any proble in jajuk.

**Comment by bflorat** [comment]
Hi Gwen,

1) we already have a script that perform some fixes in the alien deb on the IC server so I think we can use it. 

2) I think it is used by dbus (to be checked)

**Comment by gkerdal** [comment]
Hi Bertrand

1) I can't find the scripts : are they on github or just on the integration server ?

2) I'll have a look at this dbus feature (I don't know much about it)

**Comment by bflorat** [comment]
Hi Gwen,

1) only on the server, we'll have a look soon, I planned to check this out during our large integration cleanup. Maybe could we drop it all together.

2) Have a look at http://www.jajuk.info/manual/d-bus.html

**Comment by bflorat** [comment]
No more Debian package provided
