### ISSUE TITLE
Select Cover - Cannot write file

### ISSUE THREAD

**Issue by gkerdal** [jajuk-team/jajuk#2004]
On Windows 7 and Windows 10 (not reproduced on Ubuntu), when selecting a new cover a "Cannot write file" message appears and the cover is not updated.

The stacktrace : 
[ERROR] (24) Cannot write file [ERROR] class java.io.IOException / {{Invalid argument}} / null java.io.WinNTFileSystem.canonicalize0(Native Method) java.io.WinNTFileSystem.canonicalize(Unknown Source) java.io.File.getCanonicalPath(Unknown Source) org.apache.commons.io.FileUtils.copyFile(FileUtils.java:642) org.apache.commons.io.FileUtils.copyFile(FileUtils.java:607) org.jajuk.util.UtilSystem.copy(UtilSystem.java:263) org.jajuk.ui.views.CoverView$5.run(CoverView.java:639)

**Comment by bflorat** [comment]
@Gwen 
Please fix this in the develop branch (upcoming 1.11), I don't think we'll deliver another 1.10  fixpack.

**Comment by gkerdal** [comment]
OK. I just commit a fix. Tested on a Windows 10 virtual machine. Should we close this issue or wait another test ?

**Comment by bflorat** [comment]
Thx Gwen, please close the issue.
