### ISSUE TITLE
JGoodies Animation 1.4.3 patch

### ISSUE THREAD

**Issue by apoleon** [jajuk-team/jajuk#2006]
Hi,

I've updated JGoodies Animation to the latest open source version, 1.4.3, in Debian. Newer versions are closed source now. While I was working on the update I discovered that Jajuk fails to build from source with 1.4.3 now. Please find attached a patch that fixes the problem.

https://gist.github.com/apoleon/52c87999f22b224a4bbe206bacb50a2f

**Comment by bflorat** [comment]
Thanks. Applied against develop branch. Note that this lib version required a new dependency (jgoodies-common 1.6.0)

Change available at http://integration.jajuk.info:8080/job/unstable/
