### ISSUE TITLE
Ratings

### ISSUE THREAD

**Issue by Sturmprinz** [jajuk-team/jajuk#2014]
Unfortunately the ratings are just possible up to 4 stars, better would be 5 stars. Then it's a bit complicated to choose the rate from the smilie. It would be very faster, just to click on the amount of stars you want to give.

**Comment by bflorat** [comment]
Thanks for reporting. Jajuk uses by default an automatic rating system described at [1]. The smile is what we call a preference that apply a coefficient on the rating itself. 
What you want is to disable the automatic system and rate manually. You can do it by checking the "manual ratings" option in Preference view / Ratings.

Increasing from 4 to 5 stars is to be studied. Any others opinion appreciated.

[1] http://www.jajuk.info/manual/ratings.html

**Comment by centic9** [comment]
This is the same as issue #1980, so I am closing this as duplicate to have discussion about this in one place.
