### ISSUE TITLE
Jajuk fails to load following Ubuntu upgrade 17.10 to 18.10

### ISSUE THREAD

**Issue by GoMeister** [jajuk-team/jajuk#2017]
System log gives:
May  5 21:33:26 eric-Latitude-E5510 jajuk.desktop[8405]: Detected a 64-bit operating system, using the lib64 native library directory.
May  5 21:33:26 eric-Latitude-E5510 jajuk.desktop[8405]: Java version in the default path is: 10.
May  5 21:33:26 eric-Latitude-E5510 jajuk.desktop[8405]: No Java compatible version detected, but let's still try to run it!
May  5 21:33:26 eric-Latitude-E5510 jajuk.desktop[8405]: java -client -Xms20M -Xmx2G -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -Xverify:none -Djava.library.path=/usr/lib/jni:/usr/lib:/usr/share/jajuk/lib64:/usr/share/jajuk/bin/../lib/lib64 -jar jajuk.jar -notest
May  5 21:33:26 eric-Latitude-E5510 jajuk.desktop[8405]: [BOOT] Java Runtime Environment 1.7 minimum required. You use a JVM ext.JVM@7d4793a8

**Comment by bflorat** [comment]
Fixed in develop branch.
Can you please confirm this is fixed in http://integration.jajuk.info:8080/job/unstable/lastSuccessfulBuild/artifact/build/packages/jajuk_1.11.0dev_all.deb ?

**Comment by GoMeister** [comment]
Jajuk loads with following:

![image](https://user-images.githubusercontent.com/9969742/39783545-6225c3c4-530d-11e8-8b68-8a8b91ba33d7.png)

![image](https://user-images.githubusercontent.com/9969742/39783597-7f9614a4-530d-11e8-8e48-30ddefe7ffba.png)

**Comment by GoMeister** [comment]
Seemed a good time to reload the collection....  Shall I close the ticket?

**Comment by bflorat** [comment]
Thanks, please close the ticket indeed.  The version you use is unstable, it creates a separated collection in `~/.jajuk_test_<release>`  as final releases collections are stored in `~/.jajuk` directory. If you're happy with this release, changing (being root)  in /usr/bin/jajuk  `-test`to `-notest` should force it to use your current collection (please confirm). 
If you don't mind loosing your playing history / ratings... you may want just reload your collection.

**Comment by GoMeister** [comment]
Flag set to -notest and collection loads.  Many thanks!
