### ISSUE TITLE
Jajuk wont launch several machines

### ISSUE THREAD

**Issue by ch4pz** [jajuk-team/jajuk#2030]
Hi, i tried installing this on a linux mint virtual machine, and when you click from the menu it doesnt launch, nor does it launch from repository, nothing at all happens. I then tried installing on my laptop which runs ubuntu natively (obviously different pc/os/fresh install) and got the exact same thing. am i missing something? (ps im new to linux so go easy lol)

**Comment by bflorat** [comment]
Hi, please provide the jauk version you use and logs (~/.jajuk.jajuk.log)

**Comment by ch4pz** [comment]
Hi, Sorry, the Jajuk version is 1:1.10.9+dfsg2-4, and im using ubuntu 18.04. i did notice the first review on the repos. page mentions the same issue since upgrading to 18.04. although getting it in mint also. Im new to linux as a whole, how would i fetch the logs, especially considering it wont even launch?

**Comment by bflorat** [comment]
We don't support distributions packages. There are issues with last java versions, please try the last RPM at http://integration.jajuk.info:8080/job/unstable/

**Comment by centic9** [comment]
No update for a long time so I think we should close this for now, please reopen with more information as described in previous comments.
