### ISSUE TITLE
Jajuk don't open on Linux Mint 19.1

### ISSUE THREAD

**Issue by neokamen** [jajuk-team/jajuk#2032]
hello!

i have a problem.
Jajuk don't open on Linux Mint 19.1..
any solution??

a lot of thanks

**Comment by bflorat** [comment]
Hi, 
Please open a console and type 'jajuk' and send us the logs.

**Comment by neokamen** [comment]
hello bflorat!

[BOOT] Java Runtime Environment 1.7 minimum required. You use a JVM ext.JVM@7d4793a8

have a easy solution?
thanks again

**Comment by bflorat** [comment]
Please try the RPM from http://integration.jajuk.info:8080/job/unstable/
We'll release a stable ASAP.

**Comment by neokamen** [comment]
nice! thanks bflorat!!
jajuk is now open, i go try

a lot of thanks for you fast help!!

**Comment by Rudi-Ment** [comment]
Hi. 

Its to bad, the link doesnt work jet. 
Has anyone the version thats running on Linux Mint ?

Greatings

Rüdiger Haack

**Comment by bflorat** [comment]
Sorry, we'll try to release it ASAP

**Comment by Rudi-Ment** [comment]
Comming soon ?

**Comment by bflorat** [comment]
I'm on it

**Comment by bflorat** [comment]
We just released Jajuk 11. https://github.com/jajuk-team/jajuk/releases/tag/11.0
Please use the new tarball installer. We no more provide distributions packages.
