### ISSUE TITLE
refactor: move webradios URL

### ISSUE THREAD

**Issue by bflorat** [jajuk-team/jajuk#2036]
http://svn2.assembla.com/svn/common-jukebox/common-jukebox/src/main/resources/preset_radios.xml  : to be moved to github ?

**Comment by gkerdal** [comment]
I agree, what do you thinh of putting this file in the release section ?

https://github.com/jajuk-team/jajuk/releases

**Comment by bflorat** [comment]
Why not but does the final URL would then depend on the version ? 

Alternatives include :
- put it in the code but changes would then be done only for one reelase
- put it in a special branch of the repository
- put it in the github.io page at https://github.com/jajuk-team/jajuk-team.github.io

**Comment by gkerdal** [comment]
I'm not a github expert but is it possible to create a version or a tag called "Ressources" and put the preset_radios.xml file as an asset ?

**Comment by gkerdal** [comment]
According to github documentation, the tag name should follow naming convention of git tag.

So I would suggest to create a special project, jajuk-resources by exemple, to keep this kind of files.
The release would be 1.0 with the file as an asset.

The final link would be :
https://github.com/jajuk-team/jajuk-resources/releases/1.0/preset_radios.xml

If you agree, I can create the project.

**Comment by bflorat** [comment]
OK, please create a new project.

However, why using a tag version in URL ? why not : 
https://github.com/jajuk-team/jajuk-resources/master/preset_radios.xml
?

**Comment by gkerdal** [comment]
I don't have permission access on github to create a new repository for jajuk-team. Could you create it ?

You're right, I agree to point to master instead of releases, let's keep it simple.

**Comment by bflorat** [comment]
Done
https://github.com/jajuk-team/resources

**Comment by gkerdal** [comment]
I don't have commit permission or 'write access' on resources project, could you give me permission ? Thanks.

**Comment by bflorat** [comment]
I gave you admin rights on it, is it ok now ?

**Comment by gkerdal** [comment]
Yes, Thanks.

**Comment by gkerdal** [comment]
Done.
