### ISSUE TITLE
New release does not support OpenJDK or AdoptOpenJDK

### ISSUE THREAD

**Issue by mbmcf** [jajuk-team/jajuk#2043]
I am using AdoptOpenJDK on my systems to avoid Oracle licensing issues. Jajuk does not have any way to specify a non-Oracle JDK/JRE. So that means I get the message "This application requires Java Runtime environment 8.0" even though I have AdoptOpenJDK 11.05 and 8.0 installed on this windows PC.

Any way to specify the JRE/JDK I want JaJuk to use ?

Thanks,
Bruce McFarland

**Comment by bflorat** [comment]
Thanks for reporting.

I just tested Jajuk 11 successfully with AdoptOpenJDK 13 but you have to check the "Updating the JAVA_HOME environment variable" and "Updates registry keys HKLM\SOFTWARE\JavaSoft\" options in the installer to make launch4J we use in Jajuk to work as expected. 
Note that you can do it afterward if not done at the installation by relaunching the AdoptOpenJDK installer.

We'll add a note about this.
