### ISSUE TITLE
Cannot delete comment

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [jajuk-team/jajuk#2051]
Select a .mp3 file.
Press Ctrl+Enter for showing the properties.
I delete the comment and press Apply
It doesn't complain but the comment is unchanged.

**Comment by gkerdal** [comment]
Thanks for your feedback.
Problem reproduced : with an empty comment nothing happens but if the new comment is not empty, the change is taken into account.

**Comment by gkerdal** [comment]
Will be fixed in next version.

**Comment by DavidPerezIngeniero** [comment]
Thanks.  :-)
