### ISSUE TITLE
I cannot search for a word in a comment

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [jajuk-team/jajuk#2054]
I search in any field or the comment field for some word, and no results are shown, even though there are many songs with that word in the comments.

**Comment by DavidPerezIngeniero** [comment]
Discovered that I have to type the full value of the field.  I think that the default should be partial matches.
Also it is case-sensitive.  I think that the default should be case-insensitive.

**Comment by gkerdal** [comment]
Thanks for reporting. On version 11 of Jajuk I use, the search field (filter) is not case sensitive and it founds results with partial match. Could you tell us which jajuk version are you using ?

Could you also put here the result of the "copy to clipboard" function visible in the menu Help / Show debug traces, just after a search to provide more information.
Regards.

**Comment by DavidPerezIngeniero** [comment]
```
$ apt search jajuk                                                                                            ✔
jajuk/bionic,bionic 1:1.10.9+dfsg2-4 all
```

**Comment by gkerdal** [comment]
Thanks for your feedback, I will try to reproduce it.

**Comment by gkerdal** [comment]
Sorry I can't reproduce it.
Could you do the following actions : 
- in the File tables view, disable any filter, show the comment column if it's hidden and see if the comments value you're looking for are shown. if you see nothing, it's not a search problem it maybe a loading or interpretion problem of tags (OGG and FLAC have no inner COMMENT tag).
- If you see the comments, try to select the "Comment" filter and do your search.

If the problems occurs, could you post here the 2 screens before setting the filter and after ?
+ types of your files MP3/OGG/FLAC  ?

Thanks.

**Comment by DavidPerezIngeniero** [comment]
Thanks for your interest.  It is really appreciated.
I've reinstalled Jajuk, and now it works ok.
I've done a work of normalization.
Before I have comments for ID3v2.1 and 2.3, and some tracks have more than a comment tag.

**Comment by gkerdal** [comment]
Glad to read your problem is solved.
