### ISSUE TITLE
Old references of jajuk website

### ISSUE THREAD

**Issue by gkerdal** [jajuk-team/jajuk#2058]
I found some old references of the previous web site : 

[1] http://jajuk.info/index.php/Hidden_options
[2] http://jajuk.info/index.php/Installing_Perl_Audio_Converter
[3] http://jajuk.info/index.php/Tip_of_the_day

New links :
[1] http://jajuk.info/manual/hidden_options.html
[2] http://jajuk.info/manual/pacpl.html
[3] Not found

Tip_of_the_day is only present in comments of some jajuk_*.properties, we can remove the url.

**Comment by centic9** [comment]
@gkerdal, not sure why you are keeping fixed issues open with a R:Fixed label, any reason for not closing them? 

The "Milestone" Gihub-view would also work better if we can select the "open" and "closed" issues properly there.

**Comment by gkerdal** [comment]
@centic9 : I let it open waiting for the next release, so that we can see it's fixed but not yet available. You're right, it would be better to close it for the "Miltestone" view. Let's do it.
