### ISSUE TITLE
Get Java 1.8 Required message if installing on AdoptOpenJDK 1.11

### ISSUE THREAD

**Issue by mbmcf** [jajuk-team/jajuk#2059]
Hiya JaJuk Team !

I just downloaded the latest & greatest Deepest Blue onto a Windows 10 box I'm building for a friend (I5-9400, ASUS MB, 16GB, 8TB mirrored with LSI controller RAID 1, etc). I have applied all updates to the Win10 box so it has all of the latest good & not so good patches from Microsoft. Installed the latest LTS 11 JDK from AdoptOpenJDK folks. Installed JaJuk.

When I went to run JaJuk it told me that Java 1.8 was required. I guess whatever version string JaJuk is checking from Java  needs to also check for 1.11 ?

Thank you for a great product, I fire up the music box every day when I get home & it only gets turned off when I go to bed. JaJuk is the absolute best jukebox anywhere !

Bruce McFarland
Wilmington, De 19804

**Comment by gkerdal** [comment]
Hi Bruce,
thanks for reporting. I tried it on a Windows 10 virtual machine, I get the same issue.

@bflorat : it seems to come from the jajuk.exe only. No trouble if I launch Jajuk from eclipse dev environment on OpenJDK 11. Have you any ideas how to fix that ?

**Comment by bflorat** [comment]
Thanks for your interest.

Jajuk 11.0 should work with AdoptOpenJDK 11

Please check this [installation instructions](https://github.com/jajuk-team/jajuk-team.github.io/blob/master/installation.md#windows) and come back to us.

**Comment by bflorat** [comment]
Update : I just tested again and I confirm that jajuk works with the Updating the JAVA_HOME environment variable and Updates registry keys HKLM\SOFTWARE\JavaSoft options enabled when installing AdoptOpenJDK.

We need to fix some broken links in the FAQ and make this clerarer.
