### ISSUE TITLE
Deepest Blue - Didn't locate any playable files in a 1.2 TB Flac collection

### ISSUE THREAD

**Issue by mbmcf** [jajuk-team/jajuk#2063]
Hi JaJuk Team,

Running 1.10.9 version & it works fine with my jazz collection.

I went & installed the latest Deepest Blue version onto a windows 10 box, with Java 1.8.202, and when I got done the Deep Refresh the only tunes JaJuk recognized were 3 WAV files and 5 MP3's and none of the 1.2 TB of flac files.

Thinking I must have goofed something I pulled Deepest blue & reinstalled, same story. I then pulled Deepest Blue & Java too, rebooted, reinstalled java, rebooted, reinstalled Deepest Blue, and after the Deep Refresh there were still no Flac files showing.

Is there some config I have to change, or maybe something I could have missed ?

Thanks in advance for the help.

Bruce McFarland
mbmcf@verizon.net

**Comment by mbmcf** [comment]
Sorry, forgot to mention that, after all of the above, I reinstalled 1.10.9 and it found all of the flac files & correctly rebuilt the collection.

Bruce McFarland

**Comment by centic9** [comment]
If you still have logs from when it did not work we could take a look, but I think we can close it for now unless you would like to investigate some more.
