### ISSUE TITLE
Flac files stalled under Linux

### ISSUE THREAD

**Issue by bflorat** [jajuk-team/jajuk#2066]
Probably due to some issues in mplayer.1.3.0, most flac files are suddenly stalled when playing.

**Comment by bflorat** [comment]
Fix in develop

**Comment by gkerdal** [comment]
Great news, I have a majority of Flac music and this bug was really annoying.

**Comment by bflorat** [comment]
Apparently, it was an issue with mplayer 1.3.0. Seems fixed in 1.4.0. 

A great news is that I managed to build statically mplayer 1.4.0 so we will be able to embark it in the future linux appimage like Windows and OSX.
